linters-settings:
  govet:
    enable:
      - shadow
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - goimports

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor/
    - .github/
  max-issues-per-linter: 0
  max-same-issues: 0
