linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - goimports

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor/
    - .github/
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - text: "shadow:"
      linters:
        - govet
